<a href="https://colab.research.google.com/github/JoshOmondi/Loan-Predictions/blob/master/loan-pediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Loan Prediction with Various Models

####importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as mso
import seaborn as sns
import warnings
import os
import scipy

from scipy import stats
from scipy.stats import pearsonr
from scipy.stats import ttest_ind
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import CategoricalNB
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

####Uploading the file

In [2]:
from google.colab import files
files.upload()

Saving kaggle (9).json to kaggle (9).json

{'kaggle (9).json': b'{"username":"joshua10542","key":"c5f89c1c309e9609f2d67f241659b6f9"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp "kaggle (9).json" ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets list -s loan-prediction

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                    title                                                size  lastUpdated                 downloadCount  voteCount  usabilityRating
-----------------------------------------------------  ---------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
kmldas/loan-default-prediction                         Loan Default Prediction                            111675  2021-04-06 15:03:41.200000          13339        117                1
architsharma01/loan-approval-prediction-dataset        Loan-Approval-Prediction-Dataset                    82535  2023-07-16 16:31:20.923000          50133        263                1
bhavikjikadara/loan-status-prediction                  Loan Status Prediction                               5336  2024-02-02 13:27:20.870000          15465        111                1
nikhil1e9/loan-default                                 Loan Default Prediction Dataset                   8240964  2023-09-11 17:58:24.527000          27987        167                1
subhamjain/loan-prediction-based-on-customer-behavior  Loan Prediction Based on Customer Behavior        5399082  2021-08-15 18:40:27.207000          19788        287                1
ethicalstar/loan-prediction                            Loan Prediction                                   4818061  2025-03-04 06:05:49.063000           2405         40        0.7058824
devzohaib/eligibility-prediction-for-loan              Eligibility Prediction for Loan                      7983  2022-11-14 21:36:57.200000           8287         83        0.9411765
krishnaraj30/finance-loan-approval-prediction-data     Finance Loan approval Prediction Data               12824  2023-06-08 16:29:50.153000          10902        113                1
hemanthsai7/loandefault                                Loan Default prediction dataset                   9138771  2023-01-11 10:48:07.313000           7654         60        0.9411765
nabihazahid/loan-prediction-dataset-2025               Loan Prediction Dataset 2025                       864853  2025-09-14 23:03:39.450000           3546         36                1
sahilislam007/loan-factors-prediction-dataset          Loan Factors Prediction Dataset                    434827  2025-06-21 09:02:24.590000           1061         28                1
sohailkhan05/loan-risk-prediction                      Loan Risk Prediction                                74743  2026-02-28 12:13:54.570000            725         24        0.8235294
sonalisingh1411/loan-approval-prediction               Loan Approval Prediction                            13885  2021-03-22 12:21:51.233000           5125         49        0.5882353
muhammadmusharraf444/loan-approval-dataset             Loan Approval Prediction Dataset                   736039  2026-06-03 09:49:27.513000            608         24                1
mamtadhaker/lt-vehicle-loan-default-prediction         L&T Vehicle Loan Default Prediction              12085164  2019-04-18 18:36:04.797000           8478         99        0.8235294
avineshprabhakaran/loan-eligibility-prediction         Loan Eligibility Prediction DataSet                  7569  2025-10-18 06:45:56.980000           2057         28        0.8235294
altruistdelhite04/loan-prediction-problem-dataset      Loan Prediction Problem Dataset                     12888  2019-03-12 12:43:33.713000          96526        565        0.1764706
abhishekmishra08/loan-approval-datasets                Loan approval datasets for prediction              403848  2025-03-21 09:33:05.483000           2654         37        0.9411765
ankitkalauni/bank-loan-defaulter-prediction-hackathon  Bank Loan Defaulter Prediction (Hackathon)        9131913  2021-12-08 15:04:45.547000           4654         62                1
kornilovag94/bank-credit-default-loan-default          Bank Credit Default (Loan Default Prediction)   326063113  2023-06-03 14:34:49.943000           2761         50                1

In [5]:
!kaggle datasets download -d altruistdelhite04/loan-prediction-problem-dataset
!unzip -q loan-prediction-problem-dataset.zip -d loan-prediction-problem-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset
License(s): unknown
Downloading loan-prediction-problem-dataset.zip to /content
100% 12.6k/12.6k [00:00<00:00, 26.7MB/s]

####Dataset information

In [6]:
df = pd.read_csv("/content/loan-prediction-problem-dataset/train_u6lujuX_CVtuZ9i.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [8]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
# Drop rows with very few missing
df.dropna(subset=['Married'], inplace=True)

# Drop the 3 rows where Married is null
df.dropna(subset=['Married'], inplace=True)

# Numerical → median
for col in ['LoanAmount', 'Loan_Amount_Term', 'Credit_History']:
    df[col].fillna(df[col].median(), inplace=True)

# Categorical → mode
for col in ['Gender', 'Dependents', 'Self_Employed']:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Verify
df.isnull().sum()

/tmp/ipykernel_4646/1446894892.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_4646/1446894892.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64